import numpy as np

from collections.abc import Iterable

from semmatch.statistics.analyzers.base import DataAnalyzer
from semmatch.statistics.pipeline_data import AnalysisResult, MatchResult
from semmatch.statistics.data_generators import ProjectionGenerator, MaskGenerator


class SemanticMatchAnalyzer(DataAnalyzer):
    """
    Analyzes semantic matching results generated by `MaskGenerator`.

    This analyzer calculates true positives and false positives based on the
    semantic match masks and a given threshold. It can handle both single and
    iterable `GeneratedData` objects from the `MaskGenerator`.
    """
    _data_generator_depedencies = [ProjectionGenerator, MaskGenerator]
    _data_result_type = MatchResult

    def analyze(self, generated_data) -> list[AnalysisResult]:
        semantic_data = generated_data[MaskGenerator]
        projection_datas = generated_data[ProjectionGenerator]

        if not isinstance(projection_datas, Iterable):
            projection_datas = [projection_datas]
        if isinstance(semantic_data, Iterable):
            semantic_data = semantic_data[0]

        projection_data = projection_datas[0]

        projections = projection_data.projections
        valid = projection_data.valid
        masks1 = semantic_data.masks1

        xs = projections[:, 0]
        ys = projections[:, 1]

        hits = np.zeros(len(projections), dtype=bool)

        hits[valid] = masks1[np.arange(
            len(masks1))[valid], ys[valid], xs[valid]]
        misses = ~hits

        data = []
        for proj_data in projection_datas:
            inliers = proj_data.inliers

            true_positives = hits & inliers
            false_positives = misses & inliers
            false_negatives = hits & ~inliers
            true_negatives = misses & ~inliers

            data.append(MatchResult(
                threshold=proj_data.threshold,

                true_positives=true_positives.sum(),
                false_positives=false_positives.sum(),
                false_negatives=false_negatives.sum(),
                true_negatives=true_negatives.sum(),
            ))

        return data
