"""
Module: semmatch.statistics.analyzers.semantic
----------------------------------------------

This module contains analyzers for semantic matching results, specifically focusing on
evaluating matches based on object segmentation masks and projection data.
"""

import numpy as np

from collections.abc import Iterable

from semmatch.statistics.analyzers.base import DataAnalyzer
from semmatch.statistics.pipeline_data import AnalysisResult, MatchResult
from semmatch.statistics.data_generators import ProjectionGenerator, MaskGenerator


class SemanticMatchAnalyzer(DataAnalyzer):
    """
    Analyzes semantic matching results generated by `MaskGenerator`.

    This analyzer calculates true positives and false positives based on the
    semantic match masks and a given threshold. It can handle both single and
    iterable `GeneratedData` objects from the `MaskGenerator`.
    """
    _data_generator_depedencies = [ProjectionGenerator, MaskGenerator]
    _data_result_type = MatchResult

    def analyze(self, generated_data) -> list[AnalysisResult]:
        """
        Analyzes the generated semantic and projection data to determine match results.

        This method processes the masks generated by `MaskGenerator` and the projections
        from `ProjectionGenerator`. It calculates true positives, false positives,
        false negatives, and true negatives based on whether projected points fall
        within semantic masks and whether they are considered inliers by the projection
        data.

        Parameters
        ----------
        generated_data : dict[type[DataGenerator], list[GeneratedData]]
            A dictionary containing generated data, expected to have `MaskGenerator`
            and `ProjectionGenerator` as keys.
            - `MaskGenerator`: Provides `MaskData` containing `masks1` (semantic masks
              for image 1).
            - `ProjectionGenerator`: Provides `ProjectionData` objects, each containing
              `projections` (projected keypoints), `valid` (boolean array indicating
              valid projections), and `inliers` (boolean array indicating geometric inliers).

        Returns
        -------
        list[AnalysisResult]
            A list of `MatchResult` objects, one for each `ProjectionData` object
            processed, containing the calculated match statistics.
        """
        semantic_data = generated_data[MaskGenerator]
        projection_datas = generated_data[ProjectionGenerator]

        if not isinstance(projection_datas, Iterable):
            projection_datas = [projection_datas]
        if isinstance(semantic_data, Iterable):
            semantic_data = semantic_data[0]

        projection_data = projection_datas[0]

        projections = projection_data.projections
        valid = projection_data.valid
        masks1 = semantic_data.masks1

        xs = projections[:, 0]
        ys = projections[:, 1]

        hits = np.zeros(len(projections), dtype=bool)

        hits[valid] = masks1[np.arange(
            len(masks1))[valid], ys[valid], xs[valid]]
        misses = ~hits

        data = []
        for proj_data in projection_datas:
            inliers = proj_data.inliers

            true_positives = hits & inliers
            false_positives = misses & inliers
            false_negatives = hits & ~inliers
            true_negatives = misses & ~inliers

            data.append(MatchResult(
                threshold=proj_data.threshold,

                true_positives=true_positives.sum(),
                false_positives=false_positives.sum(),
                false_negatives=false_negatives.sum(),
                true_negatives=true_negatives.sum(),
            ))

        return data
